#!/bin/bash
echo "Hello, World"
mkdir -p alu-shell/io_redirections_and_filters
echo '#!/bin/bash' > alu-shell/io_redirections_and_filters/0-hello_world
echo 'echo "Hello, World"' >> alu-shell/io_redirections_and_filters/0-hello_world
chmod +x alu-shell/io_redirections_and_filters/0-hello_world

echo "This script prints 'Hello, World' followed by a new line to the standard output." > alu-shell/io_redirections_and_filters/README.md
./alu-shell/io_redirections_and_filters/0-hello_world
